obstacles:
  - name : "obs1"
    pos : [0.64,0.52]
    rot: 0.0
    half_dims : [.1, 0.05]
    shape : "box"
  - name : "obs2"
    pos : [0.24,0.42]
    rot: 0.0
    half_dims : [.02, 0.02]
    shape : "box"
